### ISSUE TITLE
Infra para Login, cuál conviene adoptar considerando avatar en la home?

### ISSUE THREAD

**Issue by MiguelGalp** [MiguelGalp/odio_oido#23]
Evaluación de infraestructura para realizar login + avatar de usuario

**Comment by rolivencia** [comment]
Auth0 tiene un pool generoso de usuarios en el tier gratuito y permite la personalización. ¿Habías pensado en algún otro?

**Comment by MiguelGalp** [comment]
Bien, sí, ahí leí los docs, voy con Auth0
