### ISSUE TITLE
Agregar labels para clasificación de los issues

### ISSUE THREAD

**Issue by rolivencia** [MiguelGalp/odio_oido#6]
Se sugiere el agregado de labels que permitan hacer más eficiente la clasificación de los issues del proyecto, tomando como base las usadas en los proyectos Sunrise Café y La Cuentoneta.

**Comment by rolivencia** [comment]
@MiguelGalp: cuando puedas dale una revisada a todos los labels creados para caracterizar los issues. Si falta alguno puede ser agregado sin problemas.

Dada la naturaleza del proyecto, tal vez también convenga agregar tas de frontend/backend. ¿Cómo lo ves?

**Comment by MiguelGalp** [comment]
Hasta ahora me resultaron perfectos los labels, muy claros y precisos. Si te parece cierro el issue.

**Comment by rolivencia** [comment]
Adelante Miguel. Comienzo ya a generar los issues relacionados a la documentación.
